// Builds the book: the Markdown in ../docs/book becomes pages in book/, the reference chapter
// comes from the core's library, and the search index, sitemap and robots.txt come along.
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import MarkdownIt from 'markdown-it';
import { loadYu } from '../src/bridge.ts';
import { encode } from '../src/share.ts';
import { yuParser } from '../src/yu-lang.ts';
import { chapterList, description, escapeHtml, highlightToHtml, slug } from '../src/book-tools.ts';

const studio = dirname(dirname(fileURLToPath(import.meta.url)));
const root = dirname(studio);
const source = join(root, 'docs', 'book');
const pages = join(studio, 'book');
const SITE = 'https://yu-lang.vercel.app';
const LANGS = ['uk', 'en'];

const WORDS = {
  uk: {
    book: 'Книга Yu',
    studio: 'Студія',
    search: 'Шукати в книзі',
    searchExample: 'Наприклад, цикл',
    open: 'Відкрити в Студії',
    input: 'Ти вводиш',
    output: 'Вивід',
    picture: 'Малюнок',
    pictureAlt: 'Що намалює цей приклад',
    previous: 'Попередній розділ',
    next: 'Наступний розділ',
    chapters: 'Розділи',
    theme: 'Змінити тему',
    other: 'English',
    skip: 'До тексту',
    nothing: 'Нічого не знайшлося',
    reference: 'Усі слова',
    referenceIntro:
      'Кожне слово мови Yu: як його писати, що воно робить і приклад. Цей розділ збирається з ядра мови, тому він завжди свіжий.',
    colours: 'Кольори',
    coloursIntro:
      'Назву кольору пиши в лапках. Підходить будь-який рід («червона», «червоне»), англійська назва, «#ff8800» або «випадковий».',
    colourName: 'Українською',
    colourEn: 'English',
    colourHex: 'Код',
  },
  en: {
    book: 'The Yu book',
    studio: 'The Studio',
    search: 'Search the book',
    searchExample: 'For example, loops',
    open: 'Open in Studio',
    input: 'You type',
    output: 'Output',
    picture: 'Picture',
    pictureAlt: 'What this example draws',
    previous: 'Previous chapter',
    next: 'Next chapter',
    chapters: 'Chapters',
    theme: 'Switch theme',
    other: 'Українською',
    skip: 'To the text',
    nothing: 'Nothing found',
    reference: 'All words',
    referenceIntro:
      'Every word of Yu: how to write it, what it does and an example. This chapter is built from the language core, so it is never out of date.',
    colours: 'Colours',
    coloursIntro:
      'Write a colour name in quotes. Ukrainian names in any gender form, English names, "#ff8800" and "random" all work.',
    colourName: 'Ukrainian',
    colourEn: 'English',
    colourHex: 'Code',
  },
};

// The seed of Options::default() in the core, so every example gives what the book's test sees.
const SEED = [0x7f4a7c15, 0x9e3779b9];
const READER = { uk: 'Юрій', en: 'Yurii' };

let reader = { printed: [], answers: [], asked: [], name: '' };
const yu = await loadYu(readFileSync(join(studio, 'public', 'yu_wasm.wasm')), {
  print: (line) => reader.printed.push(line),
  ask: () => {
    const answer = reader.answers.shift() ?? reader.name;
    reader.asked.push(answer);
    return answer;
  },
});

/** Runs an example as the book's test does: the given answers first, then the reader's name. */
function run(code, lang, answers = []) {
  reader = { printed: [], answers: [...answers], asked: [], name: READER[lang] };
  const result = yu.run(code, lang, SEED);
  if (!result.ok) throw new Error(`An example of the ${lang} book fails:\n${code}\n${result.error?.text}`);
  return { ...result, printed: reader.printed, asked: reader.asked };
}

const pictures = join(studio, 'public', 'book', 'pictures');

/** Saves a drawing under its own hash, so equal pictures share one file, and shows it. */
function picture(svg, lang) {
  const name = `${createHash('sha256').update(svg).digest('hex').slice(0, 16)}.svg`;
  writeFileSync(join(pictures, name), svg);
  const [, width, height] = svg.match(/<svg[^>]* width="(\d+)" height="(\d+)"/);
  const words = WORDS[lang];
  return (
    `<figure class="book-result"><figcaption>${words.picture}</figcaption>` +
    `<img class="picture" src="/book/pictures/${name}" width="${width}" height="${height}" alt="${words.pictureAlt}" loading="lazy" /></figure>`
  );
}
const names = yu.names();
const library = yu.library();
const parser = yuParser(
  new Set(names.keywords),
  new Set(names.builtins.flatMap((builtin) => [builtin.uk, builtin.en])),
);

/** The reference chapter, written from the core's library. */
function reference(lang) {
  const words = WORDS[lang];
  const pick = (uk, en) => (lang === 'uk' ? uk : en);
  let out = `<!-- Generated by studio/scripts/build-book.mjs from crates/yu-core/src/library.rs -->\n\n`;
  out += `# ${words.reference}\n\n${words.referenceIntro}\n\n`;
  for (const section of library.sections) {
    out += `## ${pick(section.uk, section.en)}\n\n`;
    for (const entry of section.entries) {
      out += `### ${pick(entry.uk, entry.en)} · ${pick(entry.en, entry.uk)}\n\n`;
      out += `\`${pick(entry.form_uk, entry.form_en)}\`\n\n${pick(entry.text_uk, entry.text_en)}\n\n`;
      const example = pick(entry.ex_uk, entry.ex_en);
      const { printed, asked } = run(example, lang);
      if (asked.length) out += '```input\n' + asked.join('\n') + '\n```\n\n';
      out += '```yu\n' + example + '\n```\n\n';
      if (printed.length) out += '```text\n' + printed.join('\n') + '\n```\n\n';
    }
  }
  out += `## ${words.colours}\n\n${words.coloursIntro}\n\n`;
  out += `| ${words.colourName} | ${words.colourEn} | ${words.colourHex} |\n|---|---|---|\n`;
  for (const colour of library.colors) {
    out += `| ${colour.uk} | ${colour.en} | \`${colour.hex}\` |\n`;
  }
  return out + '\n';
}

const md = new MarkdownIt({ html: true });

md.renderer.rules.fence = (tokens, index, options, env) => {
  const token = tokens[index];
  const info = token.info.trim();
  const code = token.content.replace(/\n$/, '');
  const words = WORDS[env.lang];
  if (info === 'yu' || info === 'yu-error') {
    const broken = info === 'yu-error' ? ' broken' : '';
    return (
      `<figure class="book-code${broken}">` +
      `<pre>${highlightToHtml(code, parser)}</pre>` +
      `<a class="ghost small open" href="${env.links.get(code)}">${words.open}</a>` +
      `</figure>` +
      (env.pictures.get(code) ?? '')
    );
  }
  const label = info === 'input' ? words.input : info === 'text' ? words.output : '';
  const body = `<pre class="out">${escapeHtml(code)}</pre>`;
  return label
    ? `<figure class="book-result"><figcaption>${label}</figcaption>${body}</figure>`
    : body;
};

md.renderer.rules.heading_open = (tokens, index) => {
  const tag = tokens[index].tag;
  if (tag !== 'h2' && tag !== 'h3') return `<${tag}>`;
  return `<${tag} id="${slug(tokens[index + 1].content)}">`;
};

/** A chapter as HTML; every example gets its share link and its picture first, because encoding waits. */
async function chapterHtml(markdown, lang) {
  const tokens = md.parse(markdown, {});
  const links = new Map();
  const drawn = new Map();
  let given = [];
  for (const token of tokens) {
    if (token.type !== 'fence') continue;
    const info = token.info.trim();
    const code = token.content.replace(/\n$/, '');
    if ((info === 'yu' || info === 'yu-error') && !links.has(code)) {
      links.set(code, `/#code=${await encode(code)}`);
    }
    if (info === 'yu' && !drawn.has(code)) {
      const result = run(code, lang, given);
      drawn.set(code, result.drew ? picture(result.svg, lang) : '');
    }
    given = info === 'input' ? code.split('\n') : [];
  }
  return md.renderer.render(tokens, md.options, { lang, links, pictures: drawn });
}

function page({ lang, chapter, chapters, html }) {
  const words = WORDS[lang];
  const other = lang === 'uk' ? 'en' : 'uk';
  const at = chapters.findIndex((one) => one.file === chapter.file);
  const previous = chapters[at - 1];
  const next = chapters[at + 1];
  const list = chapters
    .map((one) => {
      const current = one.file === chapter.file ? ' aria-current="page"' : '';
      return `<li><a href="${one.url}"${current}>${escapeHtml(one.title)}</a></li>`;
    })
    .join('');
  const steps = [
    previous
      ? `<a class="step" href="${previous.url}" rel="prev"><small>${words.previous}</small>← ${escapeHtml(previous.title)}</a>`
      : '<span></span>',
    next
      ? `<a class="step next" href="${next.url}" rel="next"><small>${words.next}</small>${escapeHtml(next.title)} →</a>`
      : '<span></span>',
  ].join('');
  const ld = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: chapter.title,
    inLanguage: lang,
    isPartOf: { '@type': 'Book', name: words.book, url: `${SITE}/book/` },
    author: { '@type': 'Person', name: 'Yurii Dmytrenko' },
  });
  return `<!doctype html>
<html lang="${lang}" data-theme="dark">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(chapter.title)} — ${words.book}</title>
    <meta name="description" content="${escapeHtml(description(chapter.markdown))}" />
    <meta name="color-scheme" content="dark light" />
    <link rel="icon" href="/logo.svg" type="image/svg+xml" />
    <link rel="canonical" href="${SITE}${chapter.url}" />
    <link rel="alternate" hreflang="uk" href="${SITE}/book/uk/${chapter.file}/" />
    <link rel="alternate" hreflang="en" href="${SITE}/book/en/${chapter.file}/" />
    <script>try{var t=localStorage.getItem('yu-theme');if(t)document.documentElement.dataset.theme=t}catch(e){}</script>
    <script type="application/ld+json">${ld}</script>
  </head>
  <body class="book" data-lang="${lang}">
    <a class="skip" href="#text">${words.skip}</a>
    <header class="menubar">
      <a class="logo" href="/"><img src="/logo.svg" alt="Yu Studio" width="22" height="22" /></a>
      <a class="book-name" href="/book/${lang}/01-start/">${words.book}</a>
      <div class="finder">
        <input id="book-search" class="search" type="search" placeholder="${words.searchExample}" aria-label="${words.search}" autocomplete="off" />
        <div id="book-results" class="book-results" data-nothing="${words.nothing}" hidden></div>
      </div>
      <span class="spacer"></span>
      <a class="ghost studio-link" href="/">${words.studio}</a>
      <a class="ghost" id="book-other" href="/book/${other}/${chapter.file}/" data-lang="${other}">${words.other}</a>
      <button id="book-theme" class="ghost icon" type="button" title="${words.theme}" aria-label="${words.theme}">
        <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true"><circle cx="12" cy="12" r="8" fill="none" stroke="currentColor" stroke-width="2" /><path d="M12 4a8 8 0 0 1 0 16z" fill="currentColor" /></svg>
      </button>
    </header>
    <main class="book-body">
      <nav class="chapters" aria-label="${words.chapters}">
        <details class="fold"><summary>${words.chapters}</summary></details>
        <ol>${list}</ol>
      </nav>
      <article id="text" class="chapter">${html}</article>
    </main>
    <footer class="book-foot"><div class="steps">${steps}</div></footer>
    <script type="module" src="/src/book.ts"></script>
  </body>
</html>
`;
}

/** The page at /book/: both languages, and a jump to the reader's own. */
function picker(chapters) {
  const link = (lang) =>
    `<a class="primary" href="${chapters[lang][0].url}">${WORDS[lang].book} · ${lang.toUpperCase()}</a>`;
  return `<!doctype html>
<html lang="uk" data-theme="dark">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${WORDS.uk.book} · ${WORDS.en.book}</title>
    <meta name="color-scheme" content="dark light" />
    <link rel="icon" href="/logo.svg" type="image/svg+xml" />
    <link rel="canonical" href="${SITE}/book/" />
    <script>try{var t=localStorage.getItem('yu-theme');if(t)document.documentElement.dataset.theme=t;var l=localStorage.getItem('yu-lang')||(navigator.language||'').slice(0,2);location.replace(l==='en'?'/book/en/01-start/':'/book/uk/01-start/')}catch(e){}</script>
  </head>
  <body class="book picker">
    <main class="pick">${link('uk')}${link('en')}</main>
    <script type="module" src="/src/book.ts"></script>
  </body>
</html>
`;
}

rmSync(pages, { recursive: true, force: true });
rmSync(pictures, { recursive: true, force: true });
mkdirSync(pictures, { recursive: true });
const chapters = {};
for (const lang of LANGS) {
  const dir = join(source, lang);
  writeFileSync(join(dir, '11-words.md'), reference(lang));
  const files = readdirSync(dir)
    .filter((name) => name.endsWith('.md'))
    .map((name) => ({ file: name.replace(/\.md$/, ''), markdown: readFileSync(join(dir, name), 'utf8') }));
  chapters[lang] = chapterList(files, lang).map((chapter) => ({
    ...chapter,
    markdown: files.find((one) => one.file === chapter.file).markdown,
  }));
}

for (const lang of LANGS) {
  for (const chapter of chapters[lang]) {
    const html = await chapterHtml(chapter.markdown, lang);
    const dir = join(pages, lang, chapter.file);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), page({ lang, chapter, chapters: chapters[lang], html }));
  }
  const index = chapters[lang].map(({ title, url, headings }) => ({ title, url, headings }));
  mkdirSync(join(studio, 'public', 'book'), { recursive: true });
  writeFileSync(join(studio, 'public', 'book', `search-${lang}.json`), JSON.stringify(index));
}
mkdirSync(pages, { recursive: true });
writeFileSync(join(pages, 'index.html'), picker(chapters));

const urls = ['/', '/book/', ...LANGS.flatMap((lang) => chapters[lang].map((chapter) => chapter.url))];
writeFileSync(
  join(studio, 'public', 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    urls.map((url) => `  <url><loc>${SITE}${url}</loc></url>`).join('\n') +
    `\n</urlset>\n`,
);
writeFileSync(
  join(studio, 'public', 'robots.txt'),
  `User-agent: *\nAllow: /\nSitemap: ${SITE}/sitemap.xml\n`,
);

console.log(`book: ${LANGS.map((lang) => `${lang} ${chapters[lang].length}`).join(', ')} chapters`);
